# Generated by Django 5.2.11 on 2026-02-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0002_househelpprofile_cv_location_message_otpverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('househelp', 'Employee')], default='employer', max_length=20),
        ),
    ]
