# Generated by Django 5.2.11 on 2026-02-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0003_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('househelp', 'HouseHelp')], default='employer', max_length=20),
        ),
    ]
