# Generated by Django 4.2.7 on 2026-02-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchapp', '0005_application_approved_at_application_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('househelp', 'HouseHelp'), ('manager', 'Manager')], default='employer', max_length=20),
        ),
        migrations.DeleteModel(
            name='ManagerReview',
        ),
    ]
